# -*- coding: utf-8 -*-
"""TASK -3 - Create an Application(Resume).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3S5zSOx5YaKfhueyKEOaQ1YV6tblnX6
"""

HEAD
 "<!DOCTYPE html>"
 "<!--[if lt IE 7]>"      "<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->"
 "<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->"
 "<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->"
 "<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->"
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
  </head>
  <body>
    <!--[if lt IE 7]>
      <p class="browsehappy">
        You are using an <strong>outdated</strong> browser. Please
        <a href="#">upgrade your browser</a> to improve your experience.
      </p>
    <![endif]-->
    <header>
      <h1>Srividyaa K</h1>
      <address>
        Address: <br />
        Box 564, Hyderabad<br />
        Telangana<br />
        Mail ID:
        <a href="mailto:sreeharshkrajan@gmail.com">srividyaa.g@gmail.com</a>
      </address>
    </header>
    <hr />
    <section>
      <h3>Career Goals</h3>
      <p>
        I am a Bcom Business Analytics student aspiring to be a
        Financial Analytist or an Investment Banker       </p>
    </section>
    <section>
      <h3></h3>
      </p>
    </section>
    <section>
      <h3>Skills</h3>
      <p>PHP, Wordpress, Bootstrap, C, C++, Python</p>
    </section>
    <section>
      <h3>Achievements</h3>
      <p>
        I have done many certifications and dealth with a lotof current topics.
        <br />
      </p>
    </section>
    <section>
      <h3>Hobbies and Interests</h3>
      <p>
        My hobbies are singing, dancing and playing volleyball
      </p>
    </section>
    <section>
      <h3>References</h3>
      <p>
        MyCaptain
      </p>
    </section>
    <footer>
      <span>Srividyaa G |

        Address: Hyderabad Telangana|
        <a href="mailto:srividyaa.g@gmail.com">srividyaa.g@gmail.com</a>
    </span>
    </footer>
    <script src="" async defer></script>
  </body>
</html>
=======
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
  </head>
  <body>
    <!--[if lt IE 7]>
      <p class="browsehappy">
        You are using an <strong>outdated</strong> browser. Please
        <a href="#">upgrade your browser</a> to improve your experience.
      </p>
    <![endif]-->